ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpxEU+M6bT+0jNRIXXSJThMkSJ7+5Cv1Hqy8SORNyYhWP1dhuXIOnW3kC6iCM9MadAXcNg2vz5kFDIyg9L7LrvfYcDCJ+lhTkF6BnbQt730+//ZA0v6Vkf7jDVHdTdRZmhdYmFX6cC7SIxcUBIQeXi6SXMzT3rIX3UWJ85ln//enKeKrtR02wXQIewF1tnHdkoPp7dGE/5H9zjyfY11bQ+MugKi8RSDl0budy7IS8ZBP0vX7ew3RJCDXkezHxAqg6YWyBZ0aYNynCoy0jF5mtZkUhVdxCTXF4tmI7tqTWgKElyO4Pmmup3LeUjioeRjAYRRFCnjNuKuwHQIMM7XXwN l@Mortimer.users.gowaveg.com
  - github:lsmith130
